trigger:
- none

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/staged'

stages:

- stage: Plan
  jobs:
  - job: PlanJob
    pool:
      name: mypool

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.0'

    - task: AzureCLI@2
      displayName: "Terraform Init & Plan"
      inputs:
        azureSubscription: devoptoazureconnection
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          cd $(workingDirectory)

          terraform init `
            -backend-config="resource_group_name=myResourceGroup" `
            -backend-config="storage_account_name=mystorageacct15665542178" `
            -backend-config="container_name=tfstate" `
            -backend-config="key=terraform.tfstate"

          terraform plan `
            -var-file="terraform.tfvars" `
            -out=tfplan

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(workingDirectory)/tfplan'
        artifactName: terraformPlan
        publishLocation: Container


- stage: Apply
  dependsOn: Plan
  jobs:
  - deployment: ApplyJob
    environment: terraform-approval-env
    pool:
      name: mypool

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.5.0'

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: current
              downloadType: single
              artifactName: terraformPlan
              downloadPath: '$(System.DefaultWorkingDirectory)/staged'

          - task: AzureCLI@2
            displayName: "Terraform Apply"
            inputs:
              azureSubscription: devoptoazureconnection
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                cd $(workingDirectory)

                terraform init `
                  -backend-config="resource_group_name=myResourceGroup" `
                  -backend-config="storage_account_name=mystorageacct15665542178" `
                  -backend-config="container_name=tfstate" `
                  -backend-config="key=terraform.tfstate"

                terraform apply tfplan