# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: mypool
  
variables:
  azureServiceConnection: 'devoptoazureconnection'
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)\staged'   # folder where .tf files exist
stages:
  - stage: deployment_stage
    displayName: deployment_stage

    jobs:
      - job: terraform_plan_job
        displayName: terraform_plan_job

        steps:
        - checkout: self

        - task: TerraformInstaller@1
          displayName: Terraform_install
          inputs:
            terraformVersion: 'latest'

        - task: AzureCLI@2
          displayName: Terraform Init & Apply
          inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: ps
              scriptLocation: inlineScript
              workingDirectory: $(terraformWorkingDir)
              inlineScript: |
                terraform init
                terraform validate
                terraform plan -out=tfplan
                terraform apply -auto-approve tfplan

   